// story.js - 所有对话文本（重设计版 Day 1 + 原 Day 2）
const day1Story = [
    { id: 1, bg: 'street_day', char: null, speaker: '旁白', text: '（画面从黑屏淡入，春日暖阳洒落，粉色樱花花瓣随风旋转飘落，整条石板大道如梦似幻）' },
    { id: 2, bg: 'street_day', char: null, speaker: '姬莫', text: '终于……到了。' },
    { id: 3, bg: 'street_day', char: null, speaker: '旁白', text: '（拖着沉重的行李箱，站在村口老旧的长椅旁，擦了擦额头的汗）' },
    { id: 4, bg: 'street_day', char: null, speaker: '姬莫', text: '从城市到这里，坐了整整八个小时的长途汽车……空气真不一样。' },
    { id: 5, bg: 'street_day', char: null, speaker: '姬莫', text: '（没有地铁的轰鸣，没有尾气的刺鼻，只有清甜的花香和泥土的芬芳……这地方，真的存在吗？）' },
    { id: 6, bg: 'street_day', char: null, speaker: '旁白', text: '（远处传来鸡鸣和老人的笑声，几个戴草帽的村民正挑着担子走过）' },
    { id: 7, bg: 'street_day', char: null, speaker: '姬莫', text: '母亲说，叔叔的房子就在村子最里面……希望不要太破吧。' },
    { id: 8, bg: 'street_day', char: null, speaker: '姬莫', text: '（如果这里也找不到容身之处……我真的还能回去吗？）' },
    { id: 9, bg: 'street_day', char: null, speaker: '旁白', text: '（姬莫拖着行李箱，沿着樱花大道慢慢往前走，忍不住伸手接住一片飘落的花瓣）' },
    { id: 10, bg: 'street_day', char: null, speaker: '姬莫', text: '好美……城里从来没见过这么大片的樱花。' },
    { id: 11, bg: 'shop', char: null, speaker: '旁白', text: '（路过一家挂着「布罗斯杂货」木牌的小店，玻璃橱窗里摆着新鲜的蔬菜和手工肥皂）' },
    { id: 12, bg: 'shop', char: null, speaker: '姬莫', text: '（先去问问路吧……省得走冤枉路。）' },
    { id: 13, bg: 'shop', char: null, speaker: '旁白', text: '（推开吱呀作响的木门，风铃清脆响起，一位白发老奶奶正坐在柜台后打盹）' },
    { id: 14, bg: 'shop', char: null, speaker: '姬莫', text: '您好……请问去『樱花农场』怎么走？' },
    { id: 15, bg: 'shop', char: null, speaker: '旁白', text: '（老奶奶睁开眼，仔细打量他，露出慈祥的笑容）' },
    { id: 16, bg: 'shop', char: null, speaker: '老奶奶', text: '哎呀，是小莫吧？听村长说你今天来！叔叔的农场就在村子东边，沿着这条路走到底，左转就到。' },
    { id: 17, bg: 'shop', char: null, speaker: '姬莫', text: '谢谢您……您认识我叔叔？' },
    { id: 18, bg: 'shop', char: null, speaker: '老奶奶', text: '认识认识！他以前常来买种子，还会给我带城里的报纸看。' },
    { id: 19, bg: 'shop', char: null, speaker: '姬莫', text: '（原来叔叔在这里过得这么好……我却连他的样子都快记不清了。）' },
    { id: 20, bg: 'shop', char: null, speaker: '旁白', text: '（姬莫在店里买了一瓶矿泉水和一袋面包，付钱时老奶奶多找了他两块钱）' },
    { id: 21, bg: 'street_day', char: null, speaker: '姬莫', text: '奶奶，您找多了……' },
    { id: 22, bg: 'street_day', char: null, speaker: '老奶奶', text: '新来的孩子，第一次来，送你当见面礼！' },
    { id: 23, bg: 'street_day', char: null, speaker: '姬莫', text: '那……谢谢奶奶。' },
    { id: 24, bg: 'street_day', char: null, speaker: '旁白', text: '（走出小店，继续往前走，行李箱轮子在石板路上发出规律的响声）' },
    { id: 25, bg: 'street_day', char: null, speaker: '姬莫', text: '（这里的人……好像都比城里人亲切很多。）' },
    { id: 26, bg: 'house_day', char: null, speaker: '旁白', text: '（一栋爬满青藤的木屋出现在眼前，门前有一小片菜地，旁边篱笆另一侧是另一栋相似的房子）' },
    { id: 27, bg: 'house_day', char: null, speaker: '姬莫', text: '就是这里了……叔叔的房子。' },
    { id: 28, bg: 'house_day', char: null, speaker: '姬莫', text: '（看起来比想象中干净……篱笆那头应该就是邻居了吧。）' },
    { id: 29, bg: 'house_day', char: null, speaker: '旁白', text: '（姬莫把行李箱放在门前台阶上，拿出钥匙，试着打开门锁）' },
    { id: 30, bg: 'house_day', char: null, speaker: '姬莫', text: '吱呀……' },
    { id: 31, bg: 'house_day', char: null, speaker: '旁白', text: '（门开了，一股淡淡的木头和陈年书香混杂的气味扑面而来）' },
    { id: 32, bg: 'house_day', char: null, speaker: '姬莫', text: '还好……没想象中那么破。' },
    { id: 33, bg: 'house_day', char: null, speaker: '姬莫', text: '（从今天起，这里就是我的家了……）' },
    { id: 34, bg: 'house_day', char: null, speaker: '旁白', text: '（姬莫把行李箱拖进屋，简单打开，拿出几件衣服和洗漱用品，准备先收拾客厅）' },
    { id: 35, bg: 'house_day', char: null, speaker: '姬莫', text: '呼……先把这些放好吧。' },
    { id: 36, bg: 'house_day', char: null, speaker: '旁白', text: '（突然，隔壁篱笆那边传来轻快的脚步声和哼歌声）' },
    { id: 37, bg: 'house_day', char: null, speaker: '姬莫', text: '（邻居？）' },
    { id: 38, bg: 'house_day', char: 'standard', speaker: '樱花', text: '呀——！新邻居！' },
    { id: 39, bg: 'house_day', char: 'standard', speaker: '旁白', text: '（一个粉色短发的少女从篱笆后探出头来，手里提着一个空菜篮，眼睛亮晶晶的）' },
    { id: 40, bg: 'house_day', char: 'standard', speaker: '樱花', text: '你是城里来的吧？好厉害哦～我叫樱花，就住在隔壁！' },
    { id: 41, bg: 'house_day', char: 'standard', speaker: '姬莫', text: '啊……你好。我叫姬莫。' },
    { id: 42, bg: 'house_day', char: 'standard', speaker: '姬莫', text: '我是来继承我叔叔的房子的……' },
    { id: 43, bg: 'house_day', char: 'standard', speaker: '樱花', text: '继承？！哇，那你以后就要住在这里了？太好了！村里好久没有新面孔了～' },
    { id: 44, bg: 'house_day', char: 'one_hand', speaker: '樱花', text: '城里是什么样子的呀？真的像电视里演的那样，高楼大厦到处都是吗？' },
    { id: 45, bg: 'house_day', char: 'one_hand', speaker: '樱花', text: '我从来没去过城里呢……' },
    { id: 46, bg: 'house_day', char: 'one_hand', speaker: '姬莫', text: '嗯……高楼是很多，但其实挺累的。每天挤地铁、加班到很晚。' },
    { id: 47, bg: 'house_day', char: 'one_hand', speaker: '姬莫', text: '反而这里……空气很好，花也漂亮。' },
    { id: 48, bg: 'house_day', char: 'one_hand', speaker: '樱花', text: '对吧对吧！我们村的樱花超有名的！春天的时候整条街都是粉色的！' },
    { id: 49, bg: 'house_day', char: 'both_hands', speaker: '樱花', text: '不过你看起来好没精神哦～城里人都是这样吗？' },
    { id: 50, bg: 'house_day', char: 'both_hands', speaker: '樱花', text: '要不要我带你去村里转转？保证让你精神起来！' },
    { id: 51, bg: 'house_day', char: 'both_hands', speaker: '姬莫', text: '啊……不用了，我先把行李收拾一下吧。' },
    { id: 52, bg: 'house_day', char: 'both_hands', speaker: '姬莫', text: '不过……谢谢你。' },
    { id: 53, bg: 'house_day', char: 'both_hands', speaker: '樱花', text: '那好吧～不过你可不能一直闷在家里哦！' },
    { id: 54, bg: 'house_day', char: 'both_hands', speaker: '樱花', text: '村长爷爷说，新来的邻居要好好欢迎一下呢！' },
    { id: 55, bg: 'house_day', char: 'arms_cross', speaker: '樱花', text: '其实……我一个人住在这里，有时候也会觉得有点寂寞。' },
    { id: 56, bg: 'house_day', char: 'arms_cross', speaker: '樱花', text: '奶奶去城里看病了，要过阵子才回来。' },
    { id: 57, bg: 'house_day', char: 'arms_cross', speaker: '樱花', text: '你来了之后……感觉村子一下子热闹起来了。' },
    { id: 58, bg: 'house_day', char: 'arms_cross', speaker: '姬莫', text: '是吗……那我以后会多出来走走的。' },
    { id: 59, bg: 'house_day', char: 'arms_cross', speaker: '樱花', text: '真的吗？太好了！' },
    { id: 60, bg: 'house_day', char: 'one_hand', speaker: '樱花', text: '对了！你今天刚来，肯定还没吃东西吧？' },
    { id: 61, bg: 'house_day', char: 'one_hand', speaker: '樱花', text: '我正要去小店买菜，要不要我帮你也买点？' },
    { id: 62, bg: 'house_day', char: 'one_hand', speaker: '姬莫', text: '不用不用……我自己去就行。' },
    { id: 63, bg: 'house_day', char: 'one_hand', speaker: '樱花', text: '没关系啦！我们是邻居嘛～' },
    { id: 64, bg: 'house_day', char: 'one_hand', speaker: '樱花', text: '你喜欢吃西红柿炒蛋还是土豆炖牛肉？' },
    { id: 65, bg: 'house_day', char: 'one_hand', speaker: '姬莫', text: '都……都可以。' },
    { id: 66, bg: 'house_day', char: 'one_hand', speaker: '姬莫', text: '（她说话好快……但感觉很温暖。）' },
    { id: 67, bg: 'house_day', char: 'standard', speaker: '樱花', text: '那我去买了哦！等我回来再找你玩～' },
    { id: 68, bg: 'house_day', char: 'standard', speaker: '樱花', text: '我的家就在你家右手边那栋，篱笆门上挂着粉色风铃的，就是我家！' },
    { id: 69, bg: 'house_day', char: 'standard', speaker: '姬莫', text: '好的……谢谢你，樱花。' },
    { id: 70, bg: 'house_day', char: 'standard', speaker: '樱花', text: '不客气！那我走了哦～' },
    { id: 71, bg: 'house_day', char: null, speaker: '旁白', text: '（樱花挥挥手，提着菜篮蹦蹦跳跳地沿着小路跑远了，粉色头发在阳光下闪着光）' },
    { id: 72, bg: 'house_day', char: null, speaker: '姬莫', text: '（……真是个好女孩。）' },
    { id: 73, bg: 'house_day', char: null, speaker: '旁白', text: '（目送樱花离开，转身走向屋后的菜园）' },
    { id: 74, bg: 'farm_day', char: null, speaker: '姬莫', text: '叔叔的笔记说……西红柿区在最里面。' },
    { id: 75, bg: 'farm_day', char: null, speaker: '旁白', text: '（一片嫩绿的菜地出现在眼前，架子上爬满了藤蔓，空气中弥漫着泥土和青草的香味）' },
    { id: 76, bg: 'farm_day', char: null, speaker: '姬莫', text: '哇……好大一片。' },
    { id: 77, bg: 'farm_day', char: null, speaker: '姬莫', text: '（我以前连阳台上的小盆栽都养不活……这真的能行吗？）' },
    { id: 78, bg: 'farm_day', char: null, speaker: '旁白', text: '（姬莫蹲下来，笨拙地拔起一棵杂草，结果连根带土拔了出来）' },
    { id: 79, bg: 'farm_day', char: null, speaker: '姬莫', text: '呃……' },
    { id: 80, bg: 'farm_day', char: null, speaker: '姬莫', text: '（看来要从头学起了……）' },
    { id: 81, bg: 'farm_day', char: null, speaker: '旁白', text: '（收拾好菜园，姬莫沿着村后小路往山上走，路两旁是越来越密的樱花树）' },
    { id: 82, bg: 'farm_day', char: null, speaker: '姬莫', text: '樱花说……这里有观景台。' },
    { id: 83, bg: 'mountain', char: null, speaker: '旁白', text: '（走到山顶平台，四周是粉色樱花海，远方是层层叠叠的绿色山峦和金色田野）' },
    { id: 84, bg: 'mountain', char: null, speaker: '姬莫', text: '好美……' },
    { id: 85, bg: 'mountain', char: null, speaker: '姬莫', text: '（在城里的时候，我从来没有停下来好好看过风景……）' },
    { id: 86, bg: 'mountain', char: 'standard', speaker: '樱花', text: '姬莫！？' },
    { id: 87, bg: 'mountain', char: 'standard', speaker: '旁白', text: '（樱花正坐在木质长椅上，手里拿着一本旧书，惊讶地站起来）' },
    { id: 88, bg: 'mountain', char: 'standard', speaker: '樱花', text: '你怎么也来这里了？' },
    { id: 89, bg: 'mountain', char: 'standard', speaker: '姬莫', text: '我……随便走走。' },
    { id: 90, bg: 'mountain', char: 'standard', speaker: '樱花', text: '这里是我最喜欢的地方哦！' },
    { id: 91, bg: 'mountain', char: 'standard', speaker: '樱花', text: '有时候心情不好，我就来这里坐一会儿。' },
    { id: 92, bg: 'mountain', char: 'standard', speaker: '樱花', text: '看着这些花，烦恼好像都变小了。' },
    { id: 93, bg: 'mountain', char: 'arms_cross', speaker: '姬莫', text: '我能理解。' },
    { id: 94, bg: 'mountain', char: 'arms_cross', speaker: '姬莫', text: '在城里的时候，我从来没有这种感觉。' },
    { id: 95, bg: 'mountain', char: 'arms_cross', speaker: '姬莫', text: '每天都被各种事情追着跑……从来没有停下来好好看看风景。' },
    { id: 96, bg: 'mountain', char: 'standard', speaker: '樱花', text: '那现在呢？你喜欢这里吗？' },
    { id: 97, bg: 'mountain', char: 'standard', speaker: '姬莫', text: '喜欢。' },
    { id: 98, bg: 'mountain', char: 'standard', speaker: '姬莫', text: '虽然才来一天……但是我第一次觉得，『这里可以成为我的家』。' },
    { id: 99, bg: 'mountain', char: 'standard', speaker: '樱花', text: '真的吗？太好了！' },
    { id: 100, bg: 'mountain', char: 'standard', speaker: '樱花', text: '那我们以后要一起把这个村子变得更好哦！' },
    { id: 101, bg: 'mountain', char: 'standard', speaker: '姬莫', text: '嗯……一起。' },
    { id: 102, bg: 'mountain', char: null, speaker: '旁白', text: '（两人并肩坐在长椅上，风吹过樱花树，粉色花瓣轻轻飘落在他们肩上）' },
    { id: 103, bg: 'mountain', char: null, speaker: '旁白', text: '（夕阳西下，天空染成橙红色）' },
    { id: 104, bg: 'mountain', char: 'standard', speaker: '樱花', text: '啊……天都黑了呢。' },
    { id: 105, bg: 'mountain', char: 'standard', speaker: '樱花', text: '我们该回去了。' },
    { id: 106, bg: 'mountain', char: 'standard', speaker: '姬莫', text: '嗯……今天真的谢谢你。' },
    { id: 107, bg: 'mountain', char: 'standard', speaker: '姬莫', text: '如果没有你，我可能到现在还在菜园里犯愁。' },
    { id: 108, bg: 'mountain', char: 'standard', speaker: '樱花', text: '不用谢啦～' },
    { id: 109, bg: 'mountain', char: 'standard', speaker: '樱花', text: '而且……我今天也很开心。' },
    { id: 110, bg: 'mountain', char: 'standard', speaker: '樱花', text: '很久没有和别人一起聊天、一起做事了。' },
    { id: 111, bg: 'mountain', char: 'standard', speaker: '姬莫', text: '我也是。' },
    { id: 112, bg: 'mountain', char: 'standard', speaker: '姬莫', text: '在城里的时候，我连和朋友吃饭的时间都没有。' },
    { id: 113, bg: 'mountain', char: 'standard', speaker: '樱花', text: '那以后我们就经常一起玩吧！' },
    { id: 114, bg: 'mountain', char: 'standard', speaker: '樱花', text: '明天继续来菜园哦！' },
    { id: 115, bg: 'mountain', char: 'standard', speaker: '姬莫', text: '好……明天见。' },
    { id: 116, bg: 'mountain', char: 'standard', speaker: '樱花', text: '嗯！明天见～' },
    { id: 117, bg: 'mountain', char: 'standard', speaker: '樱花', text: '记得早点睡哦！明天还要早起干活呢！' },
    { id: 118, bg: 'house_evening', char: null, speaker: '旁白', text: '（樱花朝姬莫挥手，沿着小路往下山跑去，粉色头发在夕阳下闪着光）' },
    { id: 119, bg: 'house_evening', char: null, speaker: '姬莫', text: '（……真是个好女孩。）' },
    { id: 120, bg: 'bedroom_evening', char: null, speaker: '旁白', text: '（姬莫回到木屋，推开卧室门，夕阳从窗户斜斜照进来）' },
    { id: 121, bg: 'bedroom_evening', char: null, speaker: '旁白', text: '（他坐在旧木椅上，拿出手机，打开「日记」App）' },
    { id: 122, bg: 'bedroom_evening', char: null, speaker: '姬莫', text: '今天是来到布罗斯村的第一天。' },
    { id: 123, bg: 'bedroom_evening', char: null, speaker: '姬莫', text: '房子比想象中要好，邻居……是个很活泼的女孩，叫樱花。' },
    { id: 124, bg: 'bedroom_evening', char: null, speaker: '姬莫', text: '她好像对城里的一切都很好奇……而我，却对这里的一切都觉得新鲜。' },
    { id: 125, bg: 'bedroom_evening', char: null, speaker: '姬莫', text: '或许……换个环境，真的能让我重新开始。' },
    { id: 126, bg: 'bedroom_evening', char: null, speaker: '系统', text: '第一天结束。获得「樱花的好感度 +15」' },
    { id: 127, bg: 'bedroom_evening', char: null, speaker: '系统', text: '解锁成就：『新的开始』' },
    { id: 128, bg: 'bedroom_evening', char: null, speaker: '旁白', text: '（画面渐黑，出现「Day 1 End」）' },
];

const day2Story = [
    { id: 1, bg: 'farm', char: null, speaker: '姬莫', text: '这里是......西红柿区？那边是黄瓜......叔叔的笔记写得真详细......『西红柿要搭架子』、『黄瓜要勤浇水』......我以前连花都没种过......这能行吗？' },
    // ... (保留原 Day 2 内容，略)
    { id: 37, bg: 'forest', char: 'standard', speaker: '姬莫', text: '嗯......一起。' }
];

function getStory(chapter = 1) {
    return chapter === 1 ? day1Story : day2Story;
}

window.getStory = getStory;
